#!/bin/sh

set -e # exit if any command fails

cleankey() {
    apt-key list | grep -q $1 && apt-key del $1 || true
}

if which apt-key > /dev/null; then
    apt-key add /usr/share/keyrings/nsls2-archive-keyring.gpg
    echo "Cleaning expired keys"
    cleankey 92B817BF # expired 2011-01-12
    cleankey 7433FB4B # expired 2012-03-10
    cleankey 59EC9B7E # expired 2013-01-14
    cleankey 256355F9 # expires 2014-01-13
    cleankey BE16DA67 # expires 2015-01-17
    cleankey 70FB0014 # expires 2016-01-17
    cleankey D1BE1726 # expires 2017--1-19
    cleankey 77B3C832 # expires 2018-01-18
    # The future
    #cleankey 2A9D4530 # expires 2019-01-17
    #cleankey F0D6998B # expires 2020-01-17
fi

#DEBHELPER#
